# Generated by Django 6.0.8 on 2026-08-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('lyrics', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='concerts.concert')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.song')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
