# Generated by Django 6.0.8 on 2026-08-05 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': 'Концерт', 'verbose_name_plural': 'Концерты'},
        ),
        migrations.AlterModelOptions(
            name='concertsong',
            options={'ordering': ['position'], 'verbose_name': 'Песня на концерте', 'verbose_name_plural': 'Песни на концерте'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(verbose_name='Дата концерта'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный концерт'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название концерта'),
        ),
        migrations.AlterField(
            model_name='concertsong',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='concerts.concert', verbose_name='Концерт'),
        ),
        migrations.AlterField(
            model_name='concertsong',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция в сетлисте'),
        ),
        migrations.AlterField(
            model_name='concertsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.song', verbose_name='Песня'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(verbose_name='Текст песни'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название песни'),
        ),
    ]
