# Generated by Django 6.0.8 on 2026-08-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_alter_concert_options_alter_concertsong_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='concertsong',
            constraint=models.UniqueConstraint(fields=('concert', 'song'), name='unique_song_per_concert'),
        ),
    ]
